name: Audit
on:
  push:
    branches:
      - main
    paths:
      - 'src/**.ts'
      - 'package-lock.json'
      - 'package.json'
  pull_request:
    paths:
      - 'src/**.ts'
      - 'package-lock.json'
      - 'package.json'
jobs:
  audit:
    name: Audit
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.5
        with:
          node-version: '14.x'
      - name: Find NPM Cache Directory
        id: npm-cache
        run: echo "::set-output name=path::$(npm config get cache)"
      - name: Setup NPM Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.path }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: npm ci
      - name: Execute Audit
        run: npm audit --audit-level=moderate
