name: Build and Test
on: push
jobs:
  build:
    name: Build Plugin
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - name: Locate NPM Directory
        if: steps.npm-cache.outputs.cache-hit != 'true'
        run: npm ci
      - name: Check Code
        run: npm run check
      #- name: Setup Node for Publishing
      #  with:
      #    registry-url: 'https://npm.pkg.github.com'
      #    node-version: '12.x'
      #- name: Publish to GitHub
      #  run: npm publish
      #  env:
      #    NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}