name: Documentation
on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/docs.yml
      - src/**.ts
      - package-lock.json
      - package.json
  pull_request:
    paths:
      - src/**.ts
jobs:
  docs:
    name: Documentation
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2-beta
        with:
          node-version: '14.x'
      - name: Find NPM Cache Directory
        id: npm-cache
        run: echo "::set-output name=path::$(npm config get cache)"
      - name: Setup NPM Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.path }}
          key: ${{ runner.os }}-node-${{hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: npm ci
      - name: Build Documentation
        run: npm run docs
      # TODO: Perform upload to github pages/static hosting platform of choice here
