name: Publish
on:
  push:
    tags:
      - v[0-9]+.[0-9]+.[0-9]+*
jobs:
  publish:
    name: Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.1
        with:
          node-version: '12.x'
      - name: Find NPM Cache Directory
        id: npm-cache
        run: echo "::set-output name=path::$(npm config get cache)"
      - name: Setup NPM Cache
        uses: actions/cache@v2
        with:
          path: ${{ steps.npm-cache.outputs.path }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
            ${{ runner.os }}-
      - name: Install Dependencies
        run: npm ci
      - name: Build and Check Code
        run: npm run build-and-check --if-present
      - name: Setup GitHub Packages
        uses: actions/setup-node@v2.1.1
        with:
          registry-url: 'https://npm.pkg.github.com'
          node-version: '12.x'
      - name: Publish to GitHub Packages
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ github.token }}
